### ISSUE TITLE
Bot_1 tg bot Automatic release

### ISSUE THREAD

**Issue by Ghost-LRT** [darabuchi/etsuko#1]
The robot currently needs to add automatic timing speed measurement + release function

**Comment by Luoxin** [comment]
#3

**Comment by Luoxin** [comment]
We will first support non-automatic speed measurement

**Comment by Luoxin** [comment]
finished.
I will close this issues.

**Comment by Ghost-LRT** [comment]
Please add the test results to be published in the form of pictures
